package lambdify.apigateway.kotlin

import lambdify.apigateway.Methods

/**
 * Created by miere.teixeira on 08/04/2018.
 */
class MyApp: App({

    val userResource = UserResource()

    // manually defined routes
    routes(
        Methods.POST and "/users/:id" withNoContent  userResource::saveUser,
        Methods.GET  and "/users"     with           userResource::retrieveUsers,
        Methods.GET  and "/"          with           userResource::root
    )

    // routes classes
    routers(
        TicketsRouter(),
        // generated by kapt at compile time.
        PollRepositoryRouter( userResource )
    )
})

